import Head from "next/head";
import Image from "next/image";
import MainPage from "./api/MainPage";
import styled from "styled-components";
import AppLayout from "./components/AppLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>All Round</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <MainPage />
      </AppLayout>
    </>
  );
}
